// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutomaticCode
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class DataModel : DataModelBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.ObjectModel;\r\nusing System.Data;\r\nusing S" +
                    "ystem.Text;\r\nusing System.Data.SqlClient;\r\nnamespace CHControl.");
            
            #line 12 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Manage\r\n{\r\n    public class ");
            
            #line 14 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : NotificationObject\r\n\t{\r\n\t       #region Attribute\r\n\t       ");
            
            #line 17 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

		       foreach(var item in ColumnList)
			   {
			       if(item.DataType=="nvarchar" || 
				       item.DataType=="varchar" || 
					   item.DataType=="text" || 
					   item.DataType=="char"
					   )
				   {
				        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\tprivate string m_");
            
            #line 27 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\tpublic string ");
            
            #line 28 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\tget { return m_");
            
            #line 30 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 33 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tm_");
            
            #line 35 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 36 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t}\r\n\t\t\t\t\t\t");
            
            #line 40 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

				   }
				   if(item.DataType=="date" || 
				       item.DataType=="time" || 
					   item.DataType=="datetime2" ||
					   item.DataType=="datetime"
					   )
			       {
				      if(item.Nullable=="yes")
					  {
					      
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate DateTime? m_");
            
            #line 51 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic DateTime? ");
            
            #line 52 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 54 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 57 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 59 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 60 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 64 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate DateTime m_");
            
            #line 69 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic DateTime ");
            
            #line 70 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 72 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 75 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 77 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 78 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t");
            
            #line 82 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				      
				   }

				   if(item.DataType=="int")
			       {
				     if(item.Nullable=="yes")
					  {
					      
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate int? m_");
            
            #line 92 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic int? ");
            
            #line 93 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 95 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 98 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 100 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 101 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 105 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate int m_");
            
            #line 110 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic int ");
            
            #line 111 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 113 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 116 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 118 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 119 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t");
            
            #line 123 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				   }

				   if(item.DataType=="bit")
			       {
				      if(item.Nullable=="yes")
					  {
					      
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate bool? m_");
            
            #line 132 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic bool? ");
            
            #line 133 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 135 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 138 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 140 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 141 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 145 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate bool m_");
            
            #line 150 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic bool ");
            
            #line 151 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 153 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 156 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 158 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 159 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t");
            
            #line 163 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				   }

				    if(item.DataType=="decimal" 
					|| item.DataType=="numeric"
					)
			       {
				      if(item.Nullable=="yes")
					  {
					      
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate decimal? m_");
            
            #line 174 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic decimal? ");
            
            #line 175 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 177 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 180 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 182 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 183 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 187 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate decimal m_");
            
            #line 192 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic decimal ");
            
            #line 193 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 195 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 198 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 200 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 201 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t");
            
            #line 205 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				   }
				   if(item.DataType=="uniqueidentifier")
				   {
				      if(item.Nullable=="yes")
					  {
					     
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate Guid? m_");
            
            #line 213 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic Guid? ");
            
            #line 214 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 216 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 219 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 221 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 222 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 226 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					       
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate Guid m_");
            
            #line 231 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic Guid ");
            
            #line 232 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 234 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 237 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 239 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 240 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 244 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				   }

			   }
		   
            
            #line default
            #line hidden
            this.Write(@"		   #endregion

		   #region Method
        /// <summary>
        /// 新增
        /// </summary>
        /// <returns></returns>
        public bool InsertEntity()
        {
		    StringBuilder sb = new StringBuilder();
			sb.Append(""INSERT INTO ");
            
            #line 260 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataName));
            
            #line default
            #line hidden
            this.Write("(\");\r\n\t\t    ");
            
            #line 261 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

			    int num=ColumnList.Count;
				int i=0;
				foreach(var item in ColumnList)
				{
			        i++;
					if(i==num)
					{
					   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t   sb.Append(\"");
            
            #line 270 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t   \r\n\t\t\t\t\t   ");
            
            #line 272 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					}
					else
					{
					    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tsb.Append(\"");
            
            #line 277 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name+","));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t   ");
            
            #line 278 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					}
				}
			
            
            #line default
            #line hidden
            this.Write("sb.Append(\") VALUES (\");");
            
            #line 281 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

			    int j=0;
			    foreach(var item in ColumnList)
				{
			        j++;
					if(j==num)
					{
					   if(item.DataType=="nvarchar" || 
				       item.DataType=="varchar" || 
					   item.DataType=="text" || 
					   item.DataType=="char"
					   )
					   {
					     if(item.Nullable=="no")
						 {
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t      sb.Append(");
            
            #line 297 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("==\"\" ? \"\" : \"\'\" + ");
            
            #line 297 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\"); \r\n\t\t\t\t\t        ");
            
            #line 298 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
  
						 }
					     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t   sb.Append(");
            
            #line 301 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("==\"\" ? \"NULL\" : \"\'\" + ");
            
            #line 301 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\"); \r\n\t\t\t\t\t     ");
            
            #line 302 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					   }
					   else
					   {
					       
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t     sb.Append(");
            
            #line 307 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("==null ? \"NULL\" : \"\'\" + ");
            
            #line 307 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\"); \r\n\t\t\t\t\t       ");
            
            #line 308 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					   }
					}
					else
					{  
					     if(item.DataType=="nvarchar" || 
				       item.DataType=="varchar" || 
					   item.DataType=="text" || 
					   item.DataType=="char"
					   )
					   {
					     if(item.Nullable=="no")
						 {
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t      sb.Append(");
            
            #line 322 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("==\"\" ? \"\'\'\" : \"\'\" + ");
            
            #line 322 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\" + \",\"); \r\n\t\t\t\t\t        ");
            
            #line 323 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
  
						 }
					     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t   sb.Append(");
            
            #line 326 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("==\"\" ? \"NULL\" : \"\'\" + ");
            
            #line 326 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\" + \",\"); \r\n\t\t\t\t\t     ");
            
            #line 327 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					   }
					   else
					   {
					       
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t     sb.Append(");
            
            #line 332 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("==null ? null : \"\'\" + ");
            
            #line 332 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\" + \",\"); \r\n\t\t\t\t\t       ");
            
            #line 333 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					   }
					}
				}
			
            
            #line default
            #line hidden
            this.Write(@"			sb.Append("")"");
			string sql=sb.ToString();
			int result = DB.ExecuteNonQuery(sql);
            return (result>0);
        }

        /// <summary>
        /// 更新
        /// </summary>
        /// <returns></returns>
        public bool UpdateEntity()
        {
		    StringBuilder sb = new StringBuilder();
            sb.Append(""UPDATE [dbo].[");
            
            #line 351 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataName));
            
            #line default
            #line hidden
            this.Write("] SET \");\r\n\t\t\t");
            
            #line 352 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

				       int s=0;
					   foreach(var item in ColumnList)
					   {
					      s++;
					      if(!item.IsPK)
						  {
						     if(s==num)
							  {
								 if(item.DataType=="nvarchar" || 
				                      item.DataType=="varchar" || 
					                  item.DataType=="text" || 
					                  item.DataType=="char"
					                 )
					                {
									   if(item.Nullable=="no")
									   {
									       
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t          sb.Append(\"");
            
            #line 370 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\");\r\n                                          sb.Append(");
            
            #line 371 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == \"\" ? \"\'\'\" : \"\'\" + ");
            
            #line 371 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\");\r\n\t\t\t\t\t\t\t\t          ");
            
            #line 372 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

									    }
										else
										{
										   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t             sb.Append(\"");
            
            #line 377 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\");\r\n                                             sb.Append(");
            
            #line 378 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == \"\" ? \"NULL\" : \"\'\" + ");
            
            #line 378 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\");\r\n\t\t\t\t\t\t\t\t           ");
            
            #line 379 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

										}
								           
								    }
									else
									{
									      
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t             sb.Append(\"");
            
            #line 386 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\");\r\n                                             sb.Append(");
            
            #line 387 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == null ? \"NULL\" : \"\'\" + ");
            
            #line 387 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\");\r\n\t\t\t\t\t\t\t\t           ");
            
            #line 388 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

									}
							  }
							  else
							  {
							       if(item.DataType=="nvarchar" || 
				                      item.DataType=="varchar" || 
					                  item.DataType=="text" || 
					                  item.DataType=="char"
					                 )
					                {
									   if(item.Nullable=="no")
									   {
									       
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t          sb.Append(\"");
            
            #line 402 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\");\r\n                                          sb.Append(");
            
            #line 403 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == \"\" ? \"\'\'\" : \"\'\" + ");
            
            #line 403 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\");\r\n                                          sb.Append(\",\");\r\n\t\t\t\t\t\t\t\t    " +
                    "      ");
            
            #line 405 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

									    }
										else
										{
										   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t             sb.Append(\"");
            
            #line 410 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\");\r\n                                             sb.Append(");
            
            #line 411 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == \"\" ? \"NULL\" : \"\'\" + ");
            
            #line 411 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\");\r\n                                             sb.Append(\",\");\r\n\t\t\t\t\t\t\t\t " +
                    "          ");
            
            #line 413 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

										}
								           
								    }
									else
									{
									      
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t             sb.Append(\"");
            
            #line 420 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\");\r\n                                             sb.Append(");
            
            #line 421 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == null ? \"NULL\" : \"\'\" + ");
            
            #line 421 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\");\r\n                                             sb.Append(\",\");\r\n\t\t\t\t\t\t\t\t " +
                    "          ");
            
            #line 423 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

									}
							  }
						  }
					}
				  
            
            #line default
            #line hidden
            this.Write("\t\t\t\t  sb.Append(\" WHERE \");\r\n\t\t\t\t   ");
            
            #line 430 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

				      var pklist = ColumnList.Where(p => p.IsPK).ToList();
					  int count = pklist.Count;
					  int k = 0;
					  foreach (var pk in pklist)
					  {
						   k++;
						   if (k == count)
							{
							    
								   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t     sb.Append($\"");
            
            #line 441 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("=\'{");
            
            #line 441 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("}\' \");\r\n\t\t\t\t\t\t\t\t   ");
            
            #line 442 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

								
							    
							}
							else
							{
							    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t   sb.Append($\"");
            
            #line 449 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("=\'{");
            
            #line 449 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("}\'\" + \" and \");\r\n\t\t\t\t\t\t\t\t");
            
            #line 450 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
					    }
				   
            
            #line default
            #line hidden
            this.Write(@"			 string sql = sb.ToString();	                 
			 int result = DB.ExecuteNonQuery(sql);
             return (result>0);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <returns></returns>
        public bool DeleteEntity()
        {
		         
		    
            return true;
        }

        /// <summary>
        /// 查询
        /// </summary>
        /// <param name=""sql""></param>
        /// <returns></returns>
        public ObservableCollection<");
            
            #line 475 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("> SelectEntitys(string sql)\r\n        {\r\n\t\t     ObservableCollection<");
            
            #line 477 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("> entityList=new ObservableCollection<");
            
            #line 477 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t     DataTable dt=DB.ExecuteSelect(sql).Tables[0]; \r\n\t\t\t for(int i=0;i<dt" +
                    ".Rows.Count;i++)\r\n\t\t\t {\r\n\t\t\t     ");
            
            #line 481 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" entityModel=new ");
            
            #line 481 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t\t\t ");
            
            #line 482 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

				  foreach(var item in ColumnList)
				  {
			            if(item.DataType=="nvarchar" || 
							item.DataType=="varchar" || 
							item.DataType=="text" || 
							item.DataType=="char"
							)
						{
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 492 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 492 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?\"\":dt.Rows[i][\"");
            
            #line 492 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString();\r\n\t\t\t\t\t\t\t");
            
            #line 493 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						}
						if(item.DataType=="date" || 
							item.DataType=="time" || 
							item.DataType=="datetime2" ||
							item.DataType=="datetime"
							)
						{
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 502 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 502 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(DateTime?)null:Convert.ToDateTime(dt.Rows[i][\"");
            
            #line 502 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 503 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						}
						if(item.DataType=="int")
			            {
						     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 508 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 508 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(int?)null:Convert.ToInt32(dt.Rows[i][\"");
            
            #line 508 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 509 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						}
						 if(item.DataType=="bit")
						 {
						      
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 514 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 514 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(bool?)null:Convert.ToBoolean(dt.Rows[i][\"");
            
            #line 514 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 515 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						 }
						 if(item.DataType=="decimal" 
							|| item.DataType=="numeric"
							)
						 {
						     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 522 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 522 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(decimal?)null:Convert.ToDecimal(dt.Rows[i][\"");
            
            #line 522 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 523 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						 }
						 if(item.DataType=="uniqueidentifier")
						{
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 528 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 528 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(Guid?)null:Guid.Parse(dt.Rows[i][\"");
            
            #line 528 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString());\r\n\t\t\t\t\t\t\t");
            
            #line 529 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						}
				  }
				 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t entityList.Add(entityModel);\r\n\t\t\t } \r\n            return entityList;\r\n      " +
                    "  }\r\n\r\n\t\t/// <summary>\r\n        /// 查询\r\n        /// </summary>\r\n        /// <par" +
                    "am name=\"sql\"></param>\r\n        /// <returns></returns>\r\n        public ");
            
            #line 543 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" SelectEntity(string sql)\r\n        {\r\n\t\t    ");
            
            #line 545 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" entityModel = new ");
            
            #line 545 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("();\r\n            SqlDataReader dataRead=DB.ExecuteReader(sql);\r\n            if (d" +
                    "ataRead.Read())\r\n            {\r\n\t\t\t     ");
            
            #line 549 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

				  foreach(var item in ColumnList)
				  {
			            if(item.DataType=="nvarchar" || 
							item.DataType=="varchar" || 
							item.DataType=="text" || 
							item.DataType=="char"
							)
						{
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 559 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 559 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?\"\":dataRead[\"");
            
            #line 559 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString();\r\n\t\t\t\t\t\t\t");
            
            #line 560 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						}
						if(item.DataType=="date" || 
							item.DataType=="time" || 
							item.DataType=="datetime2" ||
							item.DataType=="datetime"
							)
						{
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 569 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 569 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(DateTime?)null:Convert.ToDateTime(dataRead[\"");
            
            #line 569 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 570 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						}
						if(item.DataType=="int")
			            {
						     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 575 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 575 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(int?)null:Convert.ToInt32(dataRead[\"");
            
            #line 575 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 576 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						}
						 if(item.DataType=="bit")
						 {
						      
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 581 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 581 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(bool?)null:Convert.ToBoolean(dataRead[\"");
            
            #line 581 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 582 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						 }
						 if(item.DataType=="decimal" 
							|| item.DataType=="numeric"
							)
						 {
						     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 589 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 589 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(decimal?)null:Convert.ToDecimal(dataRead[\"");
            
            #line 589 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 590 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						 }
						 if(item.DataType=="uniqueidentifier")
						{
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 595 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 595 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(Guid?)null:Guid.Parse(dataRead[\"");
            
            #line 595 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString());\r\n\t\t\t\t\t\t\t");
            
            #line 596 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						}
				  }
				 
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t\treturn entityModel;\r\n        }\r\n        #endregion\r\n\r\n\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class DataModelBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
