// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutomaticCode
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class DataModel : DataModelBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.ObjectModel;\r\nusing System.Data;\r\nnamespa" +
                    "ce CHControl.");
            
            #line 10 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Manage\r\n{\r\n    public class ");
            
            #line 12 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : NotificationObject\r\n\t{\r\n\t       #region Attribute\r\n\t       ");
            
            #line 15 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

		       foreach(var item in ColumnList)
			   {
			       if(item.DataType=="nvarchar" || 
				       item.DataType=="varchar" || 
					   item.DataType=="text" || 
					   item.DataType=="uniqueidentifier" ||
					   item.DataType=="char"
					   )
				   {
				        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\tprivate string m_");
            
            #line 26 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\tpublic string ");
            
            #line 27 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\tget { return m_");
            
            #line 29 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 32 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tm_");
            
            #line 34 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 35 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t}\r\n\t\t\t\t\t\t");
            
            #line 39 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

				   }
				   if(item.DataType=="date" || 
				       item.DataType=="time" || 
					   item.DataType=="datetime2" ||
					   item.DataType=="datetime"
					   )
			       {
				      if(item.Nullable=="yes")
					  {
					      
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate Nullable<System.DateTime> m_");
            
            #line 50 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic Nullable<System.DateTime> ");
            
            #line 51 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 53 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 56 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 58 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 59 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 63 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate DateTime m_");
            
            #line 68 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic DateTime ");
            
            #line 69 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 71 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 74 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 76 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 77 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t");
            
            #line 81 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				      
				   }

				   if(item.DataType=="int")
			       {
				     if(item.Nullable=="yes")
					  {
					      
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate Nullable<int> m_");
            
            #line 91 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic Nullable<int> ");
            
            #line 92 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 94 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 97 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 99 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 100 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 104 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate int m_");
            
            #line 109 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic int ");
            
            #line 110 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 112 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 115 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 117 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 118 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t");
            
            #line 122 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				   }

				   if(item.DataType=="bit")
			       {
				      if(item.Nullable=="yes")
					  {
					      
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate Nullable<bool> m_");
            
            #line 131 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic Nullable<bool> ");
            
            #line 132 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 134 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 137 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 139 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 140 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 144 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate bool m_");
            
            #line 149 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic bool ");
            
            #line 150 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 152 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 155 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 157 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 158 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t");
            
            #line 162 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				   }

				    if(item.DataType=="decimal" 
					|| item.DataType=="numeric"
					)
			       {
				      if(item.Nullable=="yes")
					  {
					      
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate Nullable<decimal> m_");
            
            #line 173 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic Nullable<decimal> ");
            
            #line 174 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 176 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 179 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 181 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 182 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 186 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate decimal m_");
            
            #line 191 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic decimal ");
            
            #line 192 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 194 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 197 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 199 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 200 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t");
            
            #line 204 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				   }

			   }
		   
            
            #line default
            #line hidden
            this.Write("\t\t   #endregion\r\n\r\n\t\t   #region Method\r\n        /// <summary>\r\n        /// 新增\r\n  " +
                    "      /// </summary>\r\n        /// <returns></returns>\r\n        public bool Inser" +
                    "tEntity()\r\n        {\r\n\t\t    string sql=$@\"INSERT INTO ");
            
            #line 219 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 219 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

			    int num=ColumnList.Count;
				int i=0;
				foreach(var item in ColumnList)
				{
			        i++;
					if(i==num)
					{
					   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t   ");
            
            #line 228 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t   ");
            
            #line 229 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

					}
					else
					{
					    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t   ");
            
            #line 234 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name+","));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t   ");
            
            #line 235 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

					}
				}
			
            
            #line default
            #line hidden
            this.Write(") VALUES (");
            
            #line 238 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

			    int j=0;
			    foreach(var item in ColumnList)
				{
			        j++;
					if(j==num)
					{
					   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t   \'{");
            
            #line 246 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("}\'\r\n\t\t\t\t\t   ");
            
            #line 247 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

					}
					else
					{
					    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t   \'{");
            
            #line 252 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("}\',\r\n\t\t\t\t\t   ");
            
            #line 253 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

					}
				}
			
            
            #line default
            #line hidden
            this.Write(@")"";
			int result = DB.ExecuteNonQuery(sql);
            return (result>0);
        }

        /// <summary>
        /// 更新
        /// </summary>
        /// <returns></returns>
        public bool UpdateEntity()
        {
		    string sql=$@""UPDATE [dbo].[");
            
            #line 267 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataName));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\t\t\t\tSET \r\n\t\t\t\t ");
            
            #line 269 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

				       int s=0;
					   foreach(var item in ColumnList)
					   {
					      s++;
					      if(!item.IsPK)
						  {
						     if(s==num)
							  {
								 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t  ");
            
            #line 279 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\'{");
            
            #line 279 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("}\'\r\n\t\t\t\t\t\t\t\t ");
            
            #line 280 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

							  }
							  else
							  {
								   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t   ");
            
            #line 285 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\'{");
            
            #line 285 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("}\',\r\n\t\t\t\t\t\t\t\t  ");
            
            #line 286 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

							  }
						  }
					}
				  
            
            #line default
            #line hidden
            this.Write("\t\t\t\t  WHERE \r\n\t\t\t\t   ");
            
            #line 292 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

				      var pklist = ColumnList.Where(p => p.IsPK).ToList();
					  int count = pklist.Count;
					  int k = 0;
					  foreach (var pk in pklist)
					  {
						   k++;
						   if (k == count)
							{
							    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t  ");
            
            #line 302 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("=\'{");
            
            #line 302 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("}\'\r\n\t\t\t\t\t\t\t\t");
            
            #line 303 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t  ");
            
            #line 308 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("=\'{");
            
            #line 308 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("}\',\r\n\t\t\t\t\t\t\t\t");
            
            #line 309 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

							}
					    }
				   
            
            #line default
            #line hidden
            this.Write(@"				"";
			 int result = DB.ExecuteNonQuery(sql);
             return (result>0);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <returns></returns>
        public bool DeleteEntity()
        {
            return true;
        }

        /// <summary>
        /// 查询
        /// </summary>
        /// <param name=""sql""></param>
        /// <returns></returns>
        public ObservableCollection<");
            
            #line 332 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("> SelectEntity(string sql)\r\n        {\r\n\t\t     ObservableCollection<");
            
            #line 334 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("> entityList=new ObservableCollection<");
            
            #line 334 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t     DataTable dt=DB.ExecuteSelect(sql).Tables[0]; \r\n\t\t\t for(int i=0;i<dt" +
                    ".Rows.Count;i++)\r\n\t\t\t {\r\n\t\t\t     ");
            
            #line 338 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" entityModel=new ");
            
            #line 338 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t\t\t ");
            
            #line 339 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

				  foreach(var item in ColumnList)
				  {
			            if(item.DataType=="nvarchar" || 
							item.DataType=="varchar" || 
							item.DataType=="text" || 
							item.DataType=="uniqueidentifier" ||
							item.DataType=="char"
							)
						{
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 350 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 350 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?\"\":dt.Rows[i][\"");
            
            #line 350 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString();\r\n\t\t\t\t\t\t\t");
            
            #line 351 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

						}
						if(item.DataType=="date" || 
							item.DataType=="time" || 
							item.DataType=="datetime2" ||
							item.DataType=="datetime"
							)
						{
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 360 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 360 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(DateTime?)null:Convert.ToDateTime(dt.Rows[i][\"");
            
            #line 360 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 361 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

						}
						if(item.DataType=="int")
			            {
						     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 366 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 366 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(int?)null:Convert.ToInt32(dt.Rows[i][\"");
            
            #line 366 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 367 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

						}
						 if(item.DataType=="bit")
						 {
						      
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 372 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 372 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(bool?)null:Convert.ToBoolean(dt.Rows[i][\"");
            
            #line 372 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 373 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

						 }
						 if(item.DataType=="decimal" 
							|| item.DataType=="numeric"
							)
						 {
						     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 380 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 380 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(decimal?)null:Convert.ToDecimal(dt.Rows[i][\"");
            
            #line 380 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 381 "C:\Users\hegen\Desktop\AutomaticCode\AutomaticCode\DataModel.tt"

						 }
				  }
				 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t entityList.Add(entityModel);\r\n\t\t\t } \r\n            return entityList;\r\n      " +
                    "  }\r\n        #endregion\r\n\r\n\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class DataModelBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
