// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutomaticCode
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class DataModel : DataModelBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.ObjectModel;\r\nusing System.Data;\r\nusing S" +
                    "ystem.Text;\r\nusing System.Data.SqlClient;\r\nnamespace CHControl.");
            
            #line 12 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Manage\r\n{\r\n    public class ");
            
            #line 14 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : NotificationObject\r\n\t{\r\n\t       #region Attribute\r\n\r\n\t\t   public string Entity" +
                    "Statu { get; set; }\r\n\t       ");
            
            #line 19 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

		       foreach(var item in ColumnList)
			   {
			       if(item.DataType=="nvarchar" || 
				       item.DataType=="varchar" || 
					   item.DataType=="text" || 
					   item.DataType=="char"
					   )
				   {
				        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\tprivate string m_");
            
            #line 29 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\tpublic string ");
            
            #line 30 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\tget { return m_");
            
            #line 32 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 35 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tm_");
            
            #line 37 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 38 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t}\r\n\t\t\t\t\t\t");
            
            #line 42 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

				   }
				   if(item.DataType=="date" || 
				       item.DataType=="time" || 
					   item.DataType=="datetime2" ||
					   item.DataType=="datetime"
					   )
			       {
				      if(item.Nullable=="yes")
					  {
					      
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate DateTime? m_");
            
            #line 53 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic DateTime? ");
            
            #line 54 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 56 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 59 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 61 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 62 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 66 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate DateTime m_");
            
            #line 71 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic DateTime ");
            
            #line 72 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 74 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 77 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 79 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 80 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t");
            
            #line 84 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				      
				   }

				   if(item.DataType=="int")
			       {
				     if(item.Nullable=="yes")
					  {
					      
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate int? m_");
            
            #line 94 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic int? ");
            
            #line 95 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 97 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 100 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 102 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 103 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 107 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate int m_");
            
            #line 112 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic int ");
            
            #line 113 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 115 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 118 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 120 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 121 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t");
            
            #line 125 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				   }

				   if(item.DataType=="bit")
			       {
				      if(item.Nullable=="yes")
					  {
					      
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate bool? m_");
            
            #line 134 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic bool? ");
            
            #line 135 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 137 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 140 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 142 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 143 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 147 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate bool m_");
            
            #line 152 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic bool ");
            
            #line 153 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 155 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 158 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 160 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 161 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t");
            
            #line 165 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				   }

				    if(item.DataType=="decimal" 
					|| item.DataType=="numeric"
					)
			       {
				      if(item.Nullable=="yes")
					  {
					      
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate decimal? m_");
            
            #line 176 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic decimal? ");
            
            #line 177 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 179 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 182 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 184 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 185 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 189 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					        
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate decimal m_");
            
            #line 194 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic decimal ");
            
            #line 195 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 197 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 200 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 202 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 203 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t");
            
            #line 207 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				   }
				   if(item.DataType=="uniqueidentifier")
				   {
				      if(item.Nullable=="yes")
					  {
					     
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate Guid? m_");
            
            #line 215 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic Guid? ");
            
            #line 216 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 218 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 221 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 223 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 224 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 228 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
					  else
					  {
					       
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t\t\tprivate Guid m_");
            
            #line 233 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t\t\tpublic Guid ");
            
            #line 234 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tget { return m_");
            
            #line 236 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\t\t\t\t\t\tset\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\tif (value != m_");
            
            #line 239 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tm_");
            
            #line 241 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\t\t\t\t\t\tOnPropertyChanged(\"");
            
            #line 242 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t }\r\n\t\t\t\t\t\t\t  }\r\n\t\t\t\t\t\t\t");
            
            #line 246 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					  }
				   }

			   }
		   
            
            #line default
            #line hidden
            this.Write(@"		  
		   #endregion

		   #region Method
        /// <summary>
        /// 新增
        /// </summary>
        /// <returns></returns>
        public bool InsertEntity()
        {
		    StringBuilder sb = new StringBuilder();
			sb.Append(""INSERT INTO ");
            
            #line 263 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataName));
            
            #line default
            #line hidden
            this.Write("(\");\r\n\t\t    ");
            
            #line 264 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

			    int num=ColumnList.Count;
				int i=0;
				foreach(var item in ColumnList)
				{
			        i++;
					if(i==num)
					{
					   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t   sb.Append(\"");
            
            #line 273 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t   \r\n\t\t\t\t\t   ");
            
            #line 275 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					}
					else
					{
					    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tsb.Append(\"");
            
            #line 280 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name+","));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t   ");
            
            #line 281 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					}
				}
			
            
            #line default
            #line hidden
            this.Write("sb.Append(\") VALUES (\");");
            
            #line 284 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

			    int j=0;
			    foreach(var item in ColumnList)
				{
			        j++;
					if(j==num)
					{
					   if(item.DataType=="nvarchar" || 
				       item.DataType=="varchar" || 
					   item.DataType=="text" || 
					   item.DataType=="char"
					   )
					   {
					     if(item.Nullable=="no")
						 {
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t      sb.Append(");
            
            #line 300 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("==\"\" ? \"\" : \"\'\" + ");
            
            #line 300 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\"); \r\n\t\t\t\t\t        ");
            
            #line 301 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
  
						 }
					     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t   sb.Append(");
            
            #line 304 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("==\"\" ? \"NULL\" : \"\'\" + ");
            
            #line 304 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\"); \r\n\t\t\t\t\t     ");
            
            #line 305 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					   }
					   else
					   {
					       
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t     sb.Append(");
            
            #line 310 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("==null ? \"NULL\" : \"\'\" + ");
            
            #line 310 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\"); \r\n\t\t\t\t\t       ");
            
            #line 311 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					   }
					}
					else
					{  
					     if(item.DataType=="nvarchar" || 
				       item.DataType=="varchar" || 
					   item.DataType=="text" || 
					   item.DataType=="char"
					   )
					   {
					     if(item.Nullable=="no")
						 {
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t      sb.Append(");
            
            #line 325 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("==\"\" ? \"\'\'\" : \"\'\" + ");
            
            #line 325 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\"); \r\n\t\t\t\t\t\t\t  sb.Append(\",\");\r\n\t\t\t\t\t        ");
            
            #line 327 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
  
						 }
					     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t   sb.Append(");
            
            #line 330 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("==\"\" ? \"NULL\" : \"\'\" + ");
            
            #line 330 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\"); \r\n\t\t\t\t\t\t   sb.Append(\",\");\r\n\t\t\t\t\t     ");
            
            #line 332 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					   }
					   else
					   {
					       
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t     sb.Append(");
            
            #line 337 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("==null ? \"NULL\" : \"\'\" + ");
            
            #line 337 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\" ); \r\n\t\t\t\t\t\t\t sb.Append(\",\");\r\n\t\t\t\t\t       ");
            
            #line 339 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

					   }
					}
				}
			
            
            #line default
            #line hidden
            this.Write(@"			sb.Append("")"");
			string sql=sb.ToString();
			int result = DB.ExecuteNonQuery(sql);
            return (result>0);
        }

        /// <summary>
        /// 更新
        /// </summary>
        /// <returns></returns>
        public bool UpdateEntity()
        {
		    StringBuilder sb = new StringBuilder();
            sb.Append(""UPDATE [dbo].[");
            
            #line 357 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataName));
            
            #line default
            #line hidden
            this.Write("] SET \");\r\n\t\t\t");
            
            #line 358 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

				       int s=0;
					   foreach(var item in ColumnList)
					   {
					      s++;
					      if(!item.IsPK)
						  {
						     if(s==num)
							  {
								 if(item.DataType=="nvarchar" || 
				                      item.DataType=="varchar" || 
					                  item.DataType=="text" || 
					                  item.DataType=="char"
					                 )
					                {
									   if(item.Nullable=="no")
									   {
									       
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t          sb.Append(\"");
            
            #line 376 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\");\r\n                                          sb.Append(");
            
            #line 377 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == \"\" ? \"\'\'\" : \"\'\" + ");
            
            #line 377 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\");\r\n\t\t\t\t\t\t\t\t          ");
            
            #line 378 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

									    }
										else
										{
										   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t             sb.Append(\"");
            
            #line 383 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\");\r\n                                             sb.Append(");
            
            #line 384 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == \"\" ? \"NULL\" : \"\'\" + ");
            
            #line 384 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\");\r\n\t\t\t\t\t\t\t\t           ");
            
            #line 385 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

										}
								           
								    }
									else
									{
									      
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t             sb.Append(\"");
            
            #line 392 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\");\r\n                                             sb.Append(");
            
            #line 393 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == null ? \"NULL\" : \"\'\" + ");
            
            #line 393 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\");\r\n\t\t\t\t\t\t\t\t           ");
            
            #line 394 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

									}
							  }
							  else
							  {
							       if(item.DataType=="nvarchar" || 
				                      item.DataType=="varchar" || 
					                  item.DataType=="text" || 
					                  item.DataType=="char"
					                 )
					                {
									   if(item.Nullable=="no")
									   {
									       
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t          sb.Append(\"");
            
            #line 408 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\");\r\n                                          sb.Append(");
            
            #line 409 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == \"\" ? \"\'\'\" : \"\'\" + ");
            
            #line 409 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\");\r\n                                          sb.Append(\",\");\r\n\t\t\t\t\t\t\t\t    " +
                    "      ");
            
            #line 411 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

									    }
										else
										{
										   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t             sb.Append(\"");
            
            #line 416 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\");\r\n                                             sb.Append(");
            
            #line 417 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == \"\" ? \"NULL\" : \"\'\" + ");
            
            #line 417 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\");\r\n                                             sb.Append(\",\");\r\n\t\t\t\t\t\t\t\t " +
                    "          ");
            
            #line 419 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

										}
								           
								    }
									else
									{
									      
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t             sb.Append(\"");
            
            #line 426 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=\");\r\n                                             sb.Append(");
            
            #line 427 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == null ? \"NULL\" : \"\'\" + ");
            
            #line 427 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" + \"\'\");\r\n                                             sb.Append(\",\");\r\n\t\t\t\t\t\t\t\t " +
                    "          ");
            
            #line 429 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

									}
							  }
						  }
					}
				  
            
            #line default
            #line hidden
            this.Write("\t\t\t\t  sb.Append(\" WHERE \");\r\n\t\t\t\t   ");
            
            #line 436 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

				      var pklist = ColumnList.Where(p => p.IsPK).ToList();
					  int count = pklist.Count;
					  int k = 0;
					  foreach (var pk in pklist)
					  {
						   k++;
						   if (k == count)
							{
							    
								   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t     sb.Append($\"");
            
            #line 447 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("=\'{");
            
            #line 447 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("}\' \");\r\n\t\t\t\t\t\t\t\t   ");
            
            #line 448 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t   sb.Append($\"");
            
            #line 453 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("=\'{");
            
            #line 453 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("}\'\" + \" and \");\r\n\t\t\t\t\t\t\t\t");
            
            #line 454 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
					    }
				   
            
            #line default
            #line hidden
            this.Write(@"			 string sql = sb.ToString();	                 
			 int result = DB.ExecuteNonQuery(sql);
             return (result>0);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <returns></returns>
        public bool DeleteEntity()
        {
		    StringBuilder sb = new StringBuilder();
			sb.Append(""delete [dbo].[");
            
            #line 470 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataName));
            
            #line default
            #line hidden
            this.Write("] where \");\r\n\t\t\t    ");
            
            #line 471 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

				      
					  int ks = 0;
					  foreach (var pk in pklist)
					  {
						   ks++;
						   if (ks == count)
							{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t    sb.Append($\"");
            
            #line 480 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("=\'{");
            
            #line 480 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("}\' \");\r\n\t\t\t\t\t\t\t\t");
            
            #line 481 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t   sb.Append($\"");
            
            #line 486 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("=\'{");
            
            #line 486 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Name));
            
            #line default
            #line hidden
            this.Write("}\'\" + \" and \");\r\n\t\t\t\t\t\t\t\t");
            
            #line 487 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
					    }
				   
            
            #line default
            #line hidden
            this.Write(@"		    string sql = sb.ToString();
            int result = DB.ExecuteNonQuery(sql);
            return (result > 0);
        }

        /// <summary>
        /// 查询
        /// </summary>
        /// <param name=""sql""></param>
        /// <returns></returns>
        public ObservableCollection<");
            
            #line 501 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("> SelectEntitys(string sql)\r\n        {\r\n\t\t     ObservableCollection<");
            
            #line 503 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("> entityList=new ObservableCollection<");
            
            #line 503 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t     DataTable dt=DB.ExecuteSelect(sql).Tables[0]; \r\n\t\t\t for(int i=0;i<dt" +
                    ".Rows.Count;i++)\r\n\t\t\t {\r\n\t\t\t     ");
            
            #line 507 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" entityModel=new ");
            
            #line 507 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t\t\t ");
            
            #line 508 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

				  foreach(var item in ColumnList)
				  {
			            if(item.DataType=="nvarchar" || 
							item.DataType=="varchar" || 
							item.DataType=="text" || 
							item.DataType=="char"
							)
						{
						   
						    if(item.Nullable=="no")
							{
							     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 521 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 521 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString();\r\n\t\t\t\t\t\t\t");
            
            #line 522 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 527 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 527 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?\"\":dt.Rows[i][\"");
            
            #line 527 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString();\r\n\t\t\t\t\t\t\t");
            
            #line 528 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
						   
						}
						if(item.DataType=="date" || 
							item.DataType=="time" || 
							item.DataType=="datetime2" ||
							item.DataType=="datetime"
							)
						{
						    if(item.Nullable=="no")
							{
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 541 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=Convert.ToDateTime(dt.Rows[i][\"");
            
            #line 541 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 542 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 547 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 547 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(DateTime?)null:Convert.ToDateTime(dt.Rows[i][\"");
            
            #line 547 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 548 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
						}
						if(item.DataType=="int")
			            {
						    if(item.Nullable=="no")
							{
							 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 556 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=Convert.ToInt32(dt.Rows[i][\"");
            
            #line 556 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 557 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 562 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 562 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(int?)null:Convert.ToInt32(dt.Rows[i][\"");
            
            #line 562 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 563 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
						    
						}
						 if(item.DataType=="bit")
						 {
						    if(item.Nullable=="no")
							{
							
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 572 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=Convert.ToBoolean(dt.Rows[i][\"");
            
            #line 572 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 573 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 578 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 578 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(bool?)null:Convert.ToBoolean(dt.Rows[i][\"");
            
            #line 578 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 579 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
						 }
						 if(item.DataType=="decimal" 
							|| item.DataType=="numeric"
							)
						 {
						   if(item.Nullable=="no")
						   {
						   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 589 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=Convert.ToDecimal(dt.Rows[i][\"");
            
            #line 589 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 590 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						   }
						   else
						   {
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 595 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 595 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(decimal?)null:Convert.ToDecimal(dt.Rows[i][\"");
            
            #line 595 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 596 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

						   }
						 }
						 if(item.DataType=="uniqueidentifier")
						{
						     if(item.Nullable=="no")
						   {
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 604 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=Guid.Parse(dt.Rows[i][\"");
            
            #line 604 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString());\r\n\t\t\t\t\t\t\t");
            
            #line 605 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							  
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 610 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dt.Rows[i][\"");
            
            #line 610 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(Guid?)null:Guid.Parse(dt.Rows[i][\"");
            
            #line 610 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString());\r\n\t\t\t\t\t\t\t");
            
            #line 611 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
						}
				  }
				 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t entityList.Add(entityModel);\r\n\t\t\t } \r\n            return entityList;\r\n      " +
                    "  }\r\n\r\n\t\t/// <summary>\r\n        /// 查询\r\n        /// </summary>\r\n        /// <par" +
                    "am name=\"sql\"></param>\r\n        /// <returns></returns>\r\n        public ");
            
            #line 626 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" SelectEntity(string sql)\r\n        {\r\n\t\t    ");
            
            #line 628 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" entityModel = new ");
            
            #line 628 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("();\r\n            SqlDataReader dataRead=DB.ExecuteReader(sql);\r\n            if (d" +
                    "ataRead.Read())\r\n            {\r\n\t\t\t     ");
            
            #line 632 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

				  foreach(var item in ColumnList)
				  {
			            if(item.DataType=="nvarchar" || 
							item.DataType=="varchar" || 
							item.DataType=="text" || 
							item.DataType=="char"
							)
						{
						    if(item.Nullable=="no")
							{
							
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 644 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 644 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString();\r\n\t\t\t\t\t\t\t");
            
            #line 645 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 650 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 650 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?\"\":dataRead[\"");
            
            #line 650 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString();\r\n\t\t\t\t\t\t\t");
            
            #line 651 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
						    
						}
						if(item.DataType=="date" || 
							item.DataType=="time" || 
							item.DataType=="datetime2" ||
							item.DataType=="datetime"
							)
						{
						   if(item.Nullable=="no")
							{
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 664 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 664 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(DateTime?)null:Convert.ToDateTime(dataRead[\"");
            
            #line 664 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 665 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 670 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=Convert.ToDateTime(dataRead[\"");
            
            #line 670 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 671 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
						}
						if(item.DataType=="int")
			            {
						   if(item.Nullable=="no")
							{
						     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 679 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=Convert.ToInt32(dataRead[\"");
            
            #line 679 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 680 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 685 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 685 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(int?)null:Convert.ToInt32(dataRead[\"");
            
            #line 685 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 686 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
						}
						 if(item.DataType=="bit")
						 {
						     if(item.Nullable=="no")
							{
						      
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 694 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=Convert.ToBoolean(dataRead[\"");
            
            #line 694 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 695 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 700 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 700 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(bool?)null:Convert.ToBoolean(dataRead[\"");
            
            #line 700 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 701 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
						 }
						 if(item.DataType=="decimal" 
							|| item.DataType=="numeric"
							)
						 {

						  if(item.Nullable=="no")
							{
						     
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 712 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=Convert.ToDecimal(dataRead[\"");
            
            #line 712 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 713 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 718 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 718 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(decimal?)null:Convert.ToDecimal(dataRead[\"");
            
            #line 718 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t\t\t");
            
            #line 719 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
						 }
						 if(item.DataType=="uniqueidentifier")
						{
						   if(item.Nullable=="no")
							{
						    
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 727 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=dataRead[\"");
            
            #line 727 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"]==DBNull.Value?(Guid?)null:Guid.Parse(dataRead[\"");
            
            #line 727 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString());\r\n\t\t\t\t\t\t\t");
            
            #line 728 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
							else
							{
							 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t    entityModel.");
            
            #line 733 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=Guid.Parse(dataRead[\"");
            
            #line 733 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\"].ToString());\r\n\t\t\t\t\t\t\t");
            
            #line 734 "E:\代码生成器\AutomaticCode\AutomaticCode\DataModel.tt"

							}
						}
				  }
				 
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t\treturn entityModel;\r\n        }\r\n        #endregion\r\n\r\n\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class DataModelBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
